In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
# print shape
print(a.shape)
print(b.shape)

(2, 3)
(3,)


In [8]:
c = np.matmul(a,b)
print(c)
print(c.shape)
print(b*3)

[14 32]
(2,)
[3 6 9]


In [6]:
d = a * b
print(d)
print(d.shape)

[[ 1  4  9]
 [ 4 10 18]]
(2, 3)


In [7]:
e = np.outer(a,b)
print(e)
print(e.shape)

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
(6, 3)


In [9]:
f = np.outer(b,b)
print(f)
print(f.shape)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
(3, 3)


In [13]:
g = np.array([[1,2,3],[4,5,6],[7,8,9]])
h = np.array([1,2,3])
i = np.matmul(g[[0,0,0]],h)
print(i)
print(i.shape)

[14 14 14]
(3,)


In [14]:
def sigmoid(x):
    """
    Compute the sigmoid function for the input here.
    Arguments:
    x -- A scalar or numpy array.
    Return:
    s -- sigmoid(x)
    """

    ### YOUR CODE HERE (~1 Line)
    s = 1 / (1 + np.exp(-x))
    ### END YOUR CODE

    return s

In [21]:
print(sigmoid(g))


[[0.73105858 0.88079708 0.95257413]
 [0.98201379 0.99330715 0.99752738]
 [0.99908895 0.99966465 0.99987661]]


In [24]:
g[1:] = -g[1:]
print(g)

[[ 1  2  3]
 [-4 -5 -6]
 [-7 -8 -9]]


In [59]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2])
# print shape
print(a.shape)
print(b.shape)

(2, 3)
(2,)


In [60]:
b[:,np.newaxis] * a

array([[ 1,  2,  3],
       [ 8, 10, 12]])

In [61]:
a[0]

array([1, 2, 3])

In [62]:
a[[0,0,1,1]] += 1

In [63]:
a

array([[2, 3, 4],
       [5, 6, 7]])